### ISSUE TITLE
Sign-in Failed warning after upgrading app to lastest SDK

### ISSUE THREAD

**Issue by mikektmobile** [microsoftconnect/intune-app-wrapping-tool-ios#119]
**Describe the bug:**
We upgraded our app in the app store with the latest SDK and now users are seeing the following.    This is just an update to the app and sdk.  Customers haven’t changed configuration on admin console, they have the app listed in groups and policies and configurations like before, is there something in this new SDK that needs a configuration change in the console?

**To Reproduce**
From the app store update the latest Firstup - Intune app
Launch app and we get a sign in failed

**Expected behavior:**
Log in and enter 4 digit code to get into app since we are already logged in to the old and and this is just an update

**Screenshots and logs:**
attaching screenshot
![Screenshot 2024-06-26 at 2 09 01 PM](https://github.com/microsoftconnect/intune-app-wrapping-tool-ios/assets/54901224/4b49aa63-9775-4c15-837b-10bdaafdcce4)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: 17.5.1

**Intune app wrapping tool (please complete the following information):**
Intune wrapping tool -[19.4.0](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases)

**Additional context:**

**Comment by kanishkaBagga** [comment]
Cause:
This error occurs when the Intune App Wrapping Tool fails to detect a required app protection policy for the app. App protection policies are necessary to ensure that the app meets security requirements and can be used securely within an organization's environment.

Remediation:

Verify App Protection Policy Deployment:
Log in to the Microsoft Intune admin center.
Navigate to Apps > App protection policies.
Ensure that an app protection policy has been created for iOS devices.

Check Policy Assignment:
Confirm that the app protection policy is assigned to the appropriate security group that includes the affected user.
Navigate to the specific app protection policy and review the assignments to verify that the user’s security group is included.

Target the Specific App:
Ensure that the app protection policy specifically targets the app in question.
In the policy settings, check that the app is listed under the Targeted apps section.

Sync Policies:
After verifying and updating the app protection policies, instruct the user to sync their device with Intune to apply the latest policies.
On the user's device, open the Company Portal app and select Settings > Sync.

Verify Compliance:
Ensure that the user’s device is compliant with all other Intune policies.
Non-compliance with other policies may prevent the application of the app protection policy.

**Comment by kanishkaBagga** [comment]
@mikektmobile - Any update on this

**Comment by kanishkaBagga** [comment]
Closing this issue due to lack of updates. Feel free to reopen if the issue recurs.
