### ISSUE TITLE
Why iOS wrapping request register App registration in Microsoft Entra ID, but Android wrapping not request this?

### ISSUE THREAD

**Issue by ElytisCheng** [microsoftconnect/intune-app-wrapping-tool-ios#121]
Hi team,

I have a question about the iOS app wrapping process. According to the documentation, we need to register our app with Microsoft Entra ID: [https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#register-your-app-with-microsoft-entra-id](https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#register-your-app-with-microsoft-entra-id)

However, when I completed the Android app wrapping process, it did not require this step. Can you please clarify if registering the app with Microsoft Entra ID is a required step for iOS app wrapping? And why is it different from the Android app wrapping process?

Thank you.

**Comment by wangxiaoms** [comment]
Hi, register your app with Microsoft Entra ID is required for iOS app wrapping. The parameters -ac and -ar are required for Client ID and Redirect URI. Each app will need a unique set of these parameters. You may confirm the Android requirements in Android MAM repository.
