### ISSUE TITLE
IntuneMAMPackager is damaged and can't be opened. You should move it to the Trash

### ISSUE THREAD

**Issue by Jaya212224** [microsoftconnect/intune-app-wrapping-tool-ios#124]
**Describe the bug:**
Hi,
I'm trying to execute the command mentioned in the link below and getting the error as described in the title.
[https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#use-terminal](https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#use-terminal)

![IntueMAMPackager_Error](https://github.com/user-attachments/assets/ada7ba0b-0e7a-4d5c-bf64-a846054e545c)

MacOS Sonoma 14.6.1

**To Reproduce**
1. Download the files for the App Wrapping Tool from https://github.com/microsoftconnect/intune-app-wrapping-tool-ios
2. On Mac, extract the zip file - intune-app-wrapping-too-ios-main.zip
3. In the extracted folder, double click "Microsoft Intune Application Restrictions Packager for iOS.dmg". This will open the widow with the intuneMAPPAckager folder.
4. Locate the file "IntuneMAMPackager" as shown below and drag and drop this file to a terminal
![IntueMAMPackager2](https://github.com/user-attachments/assets/884806fa-60ef-4fb4-8915-40086c8bafac)

5. Excecute the command and Error happens

**Expected behavior:**
A new *.ipa file wrapped. In my case it's "TestMaui_Wrapped.ipa"

**Screenshots and logs:**
See all above screenshots

**Smartphone (please complete the following information):**
None

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using?  
   **19.6.0**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
  **.NET MAUI 8**

**Additional context:**
None

**Comment by wangxiaoms** [comment]
Hi could you confirm
1. What is the response if you run the command without any parameters (/Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager)?
2. Have you installed Xcode on the Mac, what is the version?

**Comment by Jaya212224** [comment]
@wangxiaoms 
What is the response if you run the command without any parameters (/Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager)?

![one](https://github.com/user-attachments/assets/b71cd4c2-972d-4936-9d47-3090143f3b4e)


Have you installed Xcode on the Mac, what is the version?
Yes. 15.4
![two](https://github.com/user-attachments/assets/16fe93d2-a9a2-41d9-a4ee-d6699fd11fda)

**Comment by wangxiaoms** [comment]
In your screenshot the directory is .../Desktop/IntuneMAMPackager, can you follow the below guide and run the command from the directory /Volumes/IntuneMAMAppPackager/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager
https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#download-the-app-wrapping-tool

**Comment by Jaya212224** [comment]
It worked. Appreciated your help.
